### ISSUE TITLE
 kubectl apply -f k8s/报错

### ISSUE THREAD

**Issue by savior-only** [ccreater222/slime#3]
kubectl apply -f k8s/

The connection to the server localhost:8080 was refused - did you specify the right host or port?

**Comment by savior-only** [comment]
docker-compose up -d已成功构建web服务在8000端口，但是k8s报错，

**Comment by ccreater222** [comment]
docker-compose 和 k8s 是两种不同的环境搭建方法。搭建好docker-compose的话直接用就可以了

**Comment by ccreater222** [comment]
k8s构建的话我在腾讯云上测试没有问题

**Comment by ccreater222** [comment]
有没有完整的报错

**Comment by savior-only** [comment]
这个就是完整的报错

**Comment by savior-only** [comment]
docker-compose up -d构建好之后，访问端口只有登录功能，输了账号密码就404了

**Comment by ccreater222** [comment]
不可能啊，有没有截图还有web容器的log

**Comment by savior-only** [comment]
<img width="853" alt="图片" src="https://user-images.githubusercontent.com/69495405/170813376-e6990efc-d131-4bdd-bed3-3f1dd7a2d099.png">
<img width="866" alt="图片" src="https://user-images.githubusercontent.com/69495405/170813390-96dd3f77-afce-4089-aa9a-586db7e255e1.png">

**Comment by savior-only** [comment]
* Environment: production
   WARNING: This is a development server. Do not use it in a production deployment.
   Use a production WSGI server instead.
 * Debug mode: off
werkzeug-_internal-_log[224] 2022-05-28 06:21:27,314:  * Running on http://127.0.0.1:5000 (Press CTRL+C to quit)
172.18.0.1 - - [28/May/2022:06:26:13 +0000] "GET / HTTP/1.1" 401 590 "-" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/101.0.0.0 Safari/537.36"
172.18.0.1 - slime [28/May/2022:06:26:53 +0000] "GET / HTTP/1.1" 403 196 "-" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/101.0.0.0 Safari/537.36"
172.18.0.1 - slime [28/May/2022:06:26:53 +0000] "GET /favicon.ico HTTP/1.1" 403 196 "http://127.0.0.1:8000/" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/101.0.0.0 Safari/537.36"
2022/05/28 06:26:53 [error] 9#9: *1 open() "/etc/apache2/htpasswd" failed (2: No such file or directory), client: 172.18.0.1, server: _, request: "GET / HTTP/1.1", host: "127.0.0.1:8000"
2022/05/28 06:26:53 [error] 9#9: *1 open() "/etc/apache2/htpasswd" failed (2: No such file or directory), client: 172.18.0.1, server: _, request: "GET /favicon.ico HTTP/1.1", host: "127.0.0.1:8000", referrer: "http://127.0.0.1:8000/"

**Comment by ccreater222** [comment]
这是basic auth错了

**Comment by ccreater222** [comment]
因为没有替换容器内的htpasswd，你可以用slime:slime登录或者git pull之后再构建下

**Comment by ccreater222** [comment]
如果是开放在公网上的话一定不要用默认密码，建议重新生成下htpasswd，教程可以参考https://www.jianshu.com/p/f4120aa561cc，然后将生成的文件放到./docker/web/htpasswd文件钟

**Comment by savior-only** [comment]
好的感谢大佬，我之前还以为直接修改hhtpasswd文件的密码

**Comment by ccreater222** [comment]
😀有什么比有人使用自己开发的东西更开心的呢

**Comment by savior-only** [comment]
这个没有登录界面吗。我的只有上图中的登陆框

**Comment by ccreater222** [comment]
只有这个
