### ISSUE TITLE
各种工具扫描日志报错

### ISSUE THREAD

**Issue by savior-only** [ccreater222/slime#4]
<img width="1177" alt="图片" src="https://user-images.githubusercontent.com/69495405/170823415-f7e12ccc-f4aa-484a-b226-812fab2cb671.png">

**Comment by savior-only** [comment]
<img width="797" alt="图片" src="https://user-images.githubusercontent.com/69495405/170823609-cbe4cd95-9e9c-400a-a67c-2b72f6d91a3c.png">
<img width="673" alt="图片" src="https://user-images.githubusercontent.com/69495405/170823621-8699c600-afd6-4afe-ab40-6e675c3fd8e6.png">
<img width="836" alt="图片" src="https://user-images.githubusercontent.com/69495405/170823636-b2751efc-24d5-4b37-a6bb-6133a26e22bb.png">

**Comment by ccreater222** [comment]
要使用连续的流程，如果其中流程里面只有skip插件，要选中它

**Comment by ccreater222** [comment]
改天加点前端提示再写下使用说明

**Comment by ccreater222** [comment]
有个验证是http还是https的地方少考虑了timeout报错

**Comment by ccreater222** [comment]
final step那里没有考虑到数据校验

**Comment by savior-only** [comment]
大佬牛逼，更新bug的时候可以一键更新就好了，哈哈哈哈哈

**Comment by ccreater222** [comment]
修好了，你重新拉下镜像就好了
