### ISSUE TITLE
资产导入导出删除及删除任务问题

### ISSUE THREAD

**Issue by savior-only** [ccreater222/slime#7]
大佬，资产多的时候不能全部导出，只能一页一页的，这个有点不方便，删除也是；
还有就是希望可以增加资产筛选功能，目前只能排序；
还有下发任务的时候好像是默认的全部资产进行扫描，我选中资产了但是好像全部资产都扫描了，而且我把新建的任务删除之后，我新增的那部分资产还在扫描，我估计是删除任务的时候没有删除进程，不但子域名爆了还扫了漏洞。

**Comment by ccreater222** [comment]
资产导入导出删除都是可以全部的，因为我没写使用文档（，我现在搞下使用文档

**Comment by ccreater222** [comment]
任务删除的bug修复了

**Comment by ccreater222** [comment]
你可以看下这个简单的使用说明：https://github.com/ccreater222/slime/blob/master/usage.md，你要导出所有和删除所有不要选择任何东西直接点删除和导出就可以了

**Comment by ccreater222** [comment]
资产筛选 其实就是使用上面的搜索框对资产进行过滤，然后你接下来的所有操作都会基于这些筛选后的资产
